"""
Django settings for BA_study_management project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1ypb5wucojbf7j6ckqfjvca=z9vcvgv1u23gtilgo@%^rlpr4n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
INTERNAL_IPS = ["127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'debug_toolbar',
    'general',
    'book_reading',
    'writing_plan',
    'exam_management',
    'literature',
    'document',
    'guide',
    'BookCollection'
]

JAZZMIN_SETTINGS = {
    "site_icon": "images/fav.png",
    "show_theme_chooser": True,
    "welcome_sign": "Welcome to Study Management Dashboard",
    "language_chooser": True,
    "icons": {
        "auth.user": "fas fa-user",
        "book_reading.book": "fas fa-book-open",
        "book_reading.course": "fa-solid fa-school",
        "book_reading.readingProgress": "fa fa-sliders",
        "book_reading.otherStudyProgress": "fa fa-sliders",
        "book_reading.readingPlan": "fa fa-fire",
        "book_reading.revise": "fa fa-exchange",
        "document.document": "fa fa-clone",
        "exam_management.exam": "fa fa-puzzle-piece",
        "exam_management.improve": "fa-solid fa-arrow-up-right-dots",
        "general.notes": "fa fa-sticky-note",
        "general.studyNote": "fa fa-sticky-note",
        "writing_plan.writingPlan": "fa fa-edit",
        "literature.author": "fa fa-address-book",
        "literature.genre": "fa fa-navicon",
        "literature.literaryWork": "fa-solid fa-book",
        "guide.guide": "fa-solid fa-circle-exclamation",
    },
    "custom_css": "css/admin.css",
}

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": {
            "items": [
                "heading",
                "|",
                "bold",
                "italic",
                "underline",
                "strikethrough",
                "|",
                "link",
                "bulletedList",
                "numberedList",
                "|",
                "insertTable",
                "blockQuote",
                "imageUpload",
                "|",
                "undo",
                "redo",
            ]
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'BA_study_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'guide.context_processors.admin_guide',
                "django.template.context_processors.i18n",
            ],
        },
    },
]

WSGI_APPLICATION = 'BA_study_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("bn", "বাংলা"),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
